name: "Translate test"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/miniforge:mpich
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: Install Python packages
          run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install .[ndsl,pyFV3,test]
        - name: Download data
          run: |
            mkdir -p test_data
            cd test_data
            wget https://portal.nccs.nasa.gov/datashare/astg/smt/pace-regression-data/8.1.3_c12_6ranks_baroclinic.physics.tar.gz
            tar -xzvf 8.1.3_c12_6ranks_baroclinic.physics.tar.gz
            cd -
        - name: Numpy Translate Test
          run: |
            pytest \
              -v -s --data_path=./test_data/8.1.3/c12_6ranks_baroclinic/physics \
              --backend=numpy \
              --threshold_overrides_file=./tests/savepoint/translate/overrides/standard.yaml \
              ./tests/savepoint

        - name: Orchestrated dace:cpu Translate Test
          run: |
            export FV3_DACEMODE=BuildAndRun
            export PACE_FLOAT_PRECISION=64
            export PACE_TEST_N_THRESHOLD_SAMPLES=0
            export OMP_NUM_THREADS=10
            export PACE_LOGLEVEL=Debug
            pytest \
              -vvv -x -s --data_path=./test_data/8.1.3/c12_6ranks_baroclinic/physics \
              --backend=dace:cpu \
              --threshold_overrides_file=./tests/savepoint/translate/overrides/standard.yaml \
              ./tests/savepoint
